import * as vscode from "vscode";

/**
 * Returns the first available language model. Tries the user's preferred Copilot
 * vendor first and falls back to "any model". Returns `undefined` when no LM
 * provider is installed/signed-in — callers should use {@link ensureLanguageModel}
 * to prompt the user instead.
 */
export async function getLanguageModel(): Promise<vscode.LanguageModelChat | undefined> {
  try {
    const preferred = await vscode.lm.selectChatModels({ vendor: "copilot" });
    if (preferred.length > 0) {
      return preferred[0];
    }
    const any = await vscode.lm.selectChatModels();
    return any[0];
  } catch {
    return undefined;
  }
}

/** As {@link getLanguageModel} but shows a one-time install hint when no provider is available. */
export async function ensureLanguageModel(): Promise<vscode.LanguageModelChat | undefined> {
  const model = await getLanguageModel();
  if (model) {
    return model;
  }
  const action = await vscode.window.showInformationMessage(
    "Todo It AI features need a language model. Install GitHub Copilot Chat or another LM provider.",
    "Find Copilot Chat",
  );
  if (action === "Find Copilot Chat") {
    void vscode.commands.executeCommand("workbench.extensions.search", "GitHub.copilot-chat");
  }
  return undefined;
}

/** Streams a single user-prompt request to completion and returns the full text. */
export async function chat(
  model: vscode.LanguageModelChat,
  prompt: string,
  token: vscode.CancellationToken,
): Promise<string> {
  const messages = [vscode.LanguageModelChatMessage.User(prompt)];
  const response = await model.sendRequest(messages, {}, token);
  let out = "";
  for await (const chunk of response.text) {
    if (token.isCancellationRequested) {
      break;
    }
    out += chunk;
  }
  return out;
}

/** Opens markdown content in an untitled document and shows the preview side-by-side. */
export async function showMarkdownResponse(title: string, markdown: string): Promise<void> {
  const header = `# ${title}\n\n_Generated by Todo It · ${new Date().toISOString().slice(0, 10)}_\n\n`;
  const doc = await vscode.workspace.openTextDocument({ language: "markdown", content: header + markdown });
  await vscode.window.showTextDocument(doc, { viewColumn: vscode.ViewColumn.Beside, preview: true });
  await vscode.commands.executeCommand("markdown.showPreviewToSide");
}
